seml:
  name: adv_trans_pgd
  executable: experiments/experiment_adv_train_transductive_pgd.py
  project_root_dir: ../..
  output_dir: log/

# seml: adv_pgd_final_train

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-10:00     # max time, D-HH:MM

fixed:
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: adv_trans
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False
  n_per_class: 20
  train_attack_params:
    continuous: False
    epochs: 10
    loss_type: tanhMargin
    base_lr: 0.1
  val_attack_params:
    epochs: 200
    loss_type: tanhMargin
    base_lr: 0.1
    #fine_tune_epochs: 0
    #keep_heuristic: WeightOnly
    #search_space_size: 100_000
    #do_synchronize: True
    #loss_type: tanhMargin
grid:
  pretrain_epochs:
    type: choice
    options:  
      - 10
  dataset:
    type: choice
    options:
      - cora 
      - cora_ml
      - citeseer
      #- pubmed
  seed:
    type: choice
    options:
     - 0
     - 1
     - 5
     - 6
     - 7
     - 8
     - 9
     - 10
     - 11
     - 12
  self_training:
    type: choice
    options:
     - True
     - False
  robust_epsilon:
    type: choice
    options:
     - 0
     - 0.05
     - 0.1
     

denseGCN:
  fixed:
    model_params:
      label: DenseGCN
      model: DenseGCN
      n_filters: 64
      dropout: 0.5

denseGPR:
  fixed:
    model_params:
      label: DenseGPRGNN
      model: DenseGPRGNN
      K: 10
      hidden: 64
      propagation: GPR_prop
      dropout_NN: 0.2
      drop_GPR: attr
  grid:
    model_params:
      dropout_GPR:
        type: choice
        options:
          - 0
  #        - 0.5

denseAPPNP:
  fixed:
    model_params:
      label: DenseAPPNP
      model: DenseGPRGNN
      K: 10
      hidden: 64
      propagation: PPNP
      alpha: 0.1
      dropout_NN: 0.2
      drop_GPR: attr
  grid:
    model_params:
      dropout_GPR:
        type: choice
        options:
          - 0
#          - 0.5

