seml:
  name: arxiv
  executable: experiments/experiment_adv_train_inductive.py
  project_root_dir: ../..
  output_dir: log/


slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 4  # num cores
    time: 2-01:00     # max time, D-HH:MM 


fixed:
  train_params:
    lr: 1e-2 
    weight_decay: 0
    patience: 200
    max_epochs: 3000
  artifact_dir: cache_arxiv
  model_storage_type: grid
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False
  pretrain_epochs: 20
  validate_every: 10
  self_training: False
  attack: PRBCD
  balance_test: True
  train_attack_params:
    epochs: 20
    loss_type: tanhMargin
    fine_tune_epochs: 0
    keep_heuristic: WeightOnly
    search_space_size: 3_000_000
    with_early_stopping: False
  val_attack_params:
    epochs: 20
    loss_type: tanhMargin
    fine_tune_epochs: 0
    keep_heuristic: WeightOnly
    search_space_size: 3_000_000
    with_early_stopping: False


grid:
  seed:
    type: choice
    options:
     - 0
     - 1
     - 5
  robust_epsilon:
    type: choice
    options:
     - 0 
     - 0.01
     - 0.02
     - 0.05
     - 0.1
  dataset:
    type: choice
    options:
     - ogbn-arxiv


gprgnn:
  fixed:
    model_params: 
      label: GPR-GNN
      model: GPRGNN
      K: 10
      hidden: 256
      propagation: GPR_prop
      drop_GPR: attr
  grid:
    model_params:
      dropout_GPR:
        type: choice
        options:
        - 0
      dropout_NN:
        type: choice
        options:
        - 0.2

gcn:
  fixed:
    model_params:
      label: Vanilla GCN
      model: GCN
      dropout: 0.5
      n_filters: [256, 256]
      gdc_params: None
      svd_params: None
      jaccard_params: None

appnp:
  fixed:
    model_params: 
      label: APPNP
      model: GPRGNN
      K: 10
      hidden: 256
      alpha: 0.1
      propagation: PPNP
      dropout_NN: 0.2
      drop_GPR: attr
      dropout_GPR: 0
