seml:
  name: advtrn_prbcd
  executable: experiments/experiment_adv_train_inductive.py
  project_root_dir: ../..
  output_dir: log/


slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 24
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 4  # num cores
    time: 0-20:00     # max time, D-HH:MM 

fixed:
  train_params:
    patience: 200
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained_ind_adv
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False
  validate_every: 1
  attack: PRBCD
  train_attack_params:
    epochs: 20
    loss_type: tanhMargin
    fine_tune_epochs: 0
    keep_heuristic: WeightOnly
    search_space_size: 1_000_000
    with_early_stopping: False
  val_attack_params:
    epochs: 20
    loss_type: tanhMargin
    fine_tune_epochs: 0
    keep_heuristic: WeightOnly
    search_space_size: 1_000_000
    with_early_stopping: False


grid:
  self_training:
    type: choice
    options:
     - False
  pretrain_epochs:
    type: choice
    options:
      - 50
      - 10
  dataset:
    type: choice
    options:
    - squirrel

gprgnn:
  fixed:
    train_params:
      lr: 1e-2
      weight_decay: 1e-2
    model_params: 
      label: GPRGNN
      model: GPRGNN
      K: 10
      hidden: 128
      propagation: GPR_prop
      dropout_NN: 0.5
      dropout_GPR: 0.0
      drop_GPR: attr
  grid:
    robust_epsilon:
      type: choice
      options:
      - 0
      - 0.05
      - 0.1
      - 0.2
    seed:
      type: choice
      options:
      - 0
      - 1
      - 5

gcn:
  fixed:
    train_params:
      lr: 1e-2
      weight_decay: 1e-2
    model_params:
      label: GCN
      model: GCN
      do_cache_adj_prep: False
      n_filters: 128
      dropout: 0.5
      svd_params: None
      jaccard_params: None
      gdc_params: None
  grid:
    robust_epsilon:
      type: choice
      options:
      - 0
    seed:
      type: choice
      options:
      - 0
      - 1
      - 5
