seml:
  name: adv_trn_ind
  executable: experiments/experiment_adv_train_inductive.py
  project_root_dir: ../..
  output_dir: log/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:00     # max time, D-HH:MM 

fixed:
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 200
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained_ind_adv_final
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False
  pretrain_epochs: 10
  validate_every: 1
  attack: LRBCD
  balance_test: True
  train_attack_params:
    epochs: 20
    loss_type: tanhMargin
    lr_factor: 2000
    fine_tune_epochs: 0
    keep_heuristic: WeightOnly
    search_space_size: 1_000_000
    with_early_stopping: False
  val_attack_params:
    epochs: 20
    loss_type: tanhMargin
    lr_factor: 2000
    fine_tune_epochs: 0
    keep_heuristic: WeightOnly
    search_space_size: 1_000_000
    with_early_stopping: False


grid:
  seed:
    type: choice
    options:
     - 0
     - 1
     - 5
  self_training:
    type: choice
    options:
     - True
     - False
  robust_epsilon:
    type: choice
    options:
     - 0
     - 0.05
     - 0.1
     - 0.2
  dataset:
    type: choice
    options:
     - cora
     - cora_ml
     - citeseer
     - pubmed


gprgnn:
  fixed:
    model_params: 
      label: GPR-GNN
      model: GPRGNN
      K: 10
      hidden: 64
      dropout_NN: 0.2
      propagation: GPR_prop
      drop_GPR: attr
  grid:
    model_params:
      dropout_GPR:
        type: choice
        options:
        - 0

appnp:
  fixed:
    model_params: 
      label: APPNP
      model: GPRGNN
      K: 10
      hidden: 64
      alpha: 0.1
      propagation: PPNP
      dropout_NN: 0.5
      drop_GPR: attr
  grid:
    model_params:
      dropout_GPR:
        type: choice
        options:
          - 0


gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      do_cache_adj_prep: False
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: None
      gdc_params: None

gat:
  fixed:
    model_params:
      label: GAT
      model: GAT
      hidden_dim: 64
      dropout: 0.5

  