seml:
  name: advtrn_lrbcd05
  executable: experiments/experiment_adv_train_inductive.py
  project_root_dir: ../..
  output_dir: log/

slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 4
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 4  # num cores
    time: 0-20:00     # max time, D-HH:MM 

fixed:
  train_params:
    lr: 1e-1
    patience: 200
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained_ind_adv
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False
  pretrain_epochs: 50
  validate_every: 1
  attack: LRBCD
  balance_test: True
  train_attack_params:
    epochs: 20
    loss_type: tanhMargin
    lr_factor: 2000
    local_factor: 0.5
    fine_tune_epochs: 0
    keep_heuristic: WeightOnly
    search_space_size: 1_000_000
    with_early_stopping: False
  val_attack_params:
    epochs: 20
    loss_type: tanhMargin
    lr_factor: 2000
    local_factor: 0.5
    fine_tune_epochs: 0
    keep_heuristic: WeightOnly
    search_space_size: 1_000_000
    with_early_stopping: False

grid:
  self_training:
    type: choice
    options:
     - True
  robust_epsilon:
    type: choice
    options:
     - 0
     - 0.05
     - 0.1
     - 0.2
  dataset:
    type: choice
    options:
     - sbm_hetero


gprgnn:
  fixed:
    train_params:
      weight_decay: 1e-2
    model_params: 
      label: GPRGNN
      model: GPRGNN
      K: 10
      hidden: 64
      propagation: GPR_prop
      dropout_NN: 0.5
      dropout_GPR: 0.2
      drop_GPR: attr
  grid:
    seed:
      type: choice
      options:
      - 0
      - 1
      - 5

gcn:
  fixed:
    train_params:
      weight_decay: 1e-3
    model_params:
      label: GCN
      model: GCN
      do_cache_adj_prep: False
      n_filters: 32
      dropout: 0.2
      svd_params: None
      jaccard_params: None
      gdc_params: None
  grid:
    seed:
      type: choice
      options:
      - 0
      - 1
      - 5

  