seml:
  name: eval_ind
  executable: experiments/experiment_attack.py
  project_root_dir: ../..
  output_dir: log/eval

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:30     # max time, D-HH:MM

# seml adv_ind_final_eval_0

fixed:
  data_dir: data/
  artifact_dir: cache
  model_storage_type: pretrained_ind_adv
  pert_adj_storage_type: pretrained_ind_adv_adj
  pert_attr_storage_type: pretrained_ind_adv_attr
  device: 0
  data_device: 0
  make_undirected: True
  idx_to_attack: test
  split_type: inductive
  balance_test: True
  n_per_class: 20
  binary_attr: False
  attack: CPRBCD
  attack_params:
    epochs: 500
    fine_tune_epochs: 100
    keep_heuristic: WeightOnly
    search_space_size: 1_000_000
    do_synchronize: True
    lr_factor: 100
    loss_type: tanhMargin
    local_factor: 0.5
  model_params_add:
    attack: CPRBCD
    self_training: True
    train_attack_params_local_factor: 0.5

grid:
  model_params_add:
    robust_epsilon:
        type: choice
        options:
          - 0
          - 0.05
          - 0.1
          - 0.2
    # attack:
    #     type: choice
    #     options:
    #       - PRBCD
    #       - CPRBCD
  dataset:
    type: choice
    options:
      - wikics
  epsilons: 
    type: choice
    options:
      - [0, 0.05, 0.1, 0.25]


GPRGNN:
  fixed:
    model_label: GPRGNN

  grid:
    seed:
      type: choice
      options:
        - 0
        - 1
        - 5

GPRGNNK3:
  fixed:
    model_label: GPRGNNK3

  grid:
    seed:
      type: choice
      options:
        - 0
        - 1
        - 5

GCN:
  fixed:
    model_label: GCN

  grid:
    seed:
      type: choice
      options:
        - 0
        - 1
        - 5

# cprbcd:
#   fixed:
#     binary_attr: False
#     attack: CPRBCD
#     attack_params:
#       epochs: 400
#       fine_tune_epochs: 0
#       with_early_stopping: False
#       keep_heuristic: WeightOnly
#       search_space_size: 500_000
#       do_synchronize: True
#       lr_factor: 100
#       loss_type: tanhMargin
#   grid:
#     attack_params:
#       local_factor:
#         type: choice
#         options:
#           - 0.5
#       projection_type:
#         type: choice
#         options:
#           - Greedy
      
