seml:
  name: robust_diffusion_attack_evasion_global_direct
  executable: experiments/experiment_attack.py
  project_root_dir: ../..
  output_dir: log/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:20     # max time, D-HH:MM

fixed:
  data_dir: data/
  artifact_dir: cache
  pert_adj_storage_type: adv_trans_adj
  pert_attr_storage_type: adv_trans_attr
  model_storage_type: adv_trans
  device: 0
  data_device: 0
  make_undirected: True
  n_per_class: 20
  idx_to_attack: test
  split_type: transductive

grid:
  dataset:
    type: choice
    options:
      - cora
      - cora_ml
      - citeseer
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
  epsilons: 
    type: choice
    options:
      - [0, 0.01, 0.05, 0.10, 0.25, 0.5, 1]
  model_params_add:
    dropout_GPR:
      type: choice
      options:
        - 0
    self_training:
      type: choice
      options:
        - True
        - False
    train_attack_params_epochs:
      type: choice
      options:
        - 10
    pretrain_epochs:
      type: choice
      options:  
        - 10
    robust_epsilon:
      type: choice
      options:
      - 0
      - 0.05
      - 0.1
  model_label:
    type: choice
    options:
     - DenseGCN
     - DenseGPRGNN
     - DenseAPPNP

pgd:
  fixed:
    attack: PGD
  grid:
    attack_params:
      base_lr: 
        type: choice
        options:
          #- 1e-2
          - 1e-1
          #- 1
          #- 10
          #- 100
          #- 1000
      epochs:
        type: choice
        options:
          - 400
      attack_loss_type: 
        type: choice
        options:
          - tanhMargin
