seml:
  name: eval_ind
  executable: experiments/experiment_attack.py
  project_root_dir: ../..
  output_dir: log/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:30     # max time, D-HH:MM

fixed:
  data_dir: data/
  artifact_dir: cache
  model_storage_type: pretrained_ind_adv
  pert_adj_storage_type: pretrained_ind_adv_adj
  pert_attr_storage_type: pretrained_ind_adv_attr
  device: 0
  data_device: 0
  make_undirected: True
  idx_to_attack: test
  split_type: inductive
  balance_test: True
  n_per_class: 20
  binary_attr: False
  load_perturbed_adj: False
  save_artifacts: False
  attack: PRBCD
  attack_params:
    epochs: 500
    fine_tune_epochs: 100
    keep_heuristic: WeightOnly
    search_space_size: 1_000_000
    do_synchronize: True
    lr_factor: 100
    loss_type: tanhMargin
  model_params_add:
    attack: PRBCD
    self_training: False
    pretrain_epochs: 50

grid:
  dataset:
    type: choice
    options:
      - squirrel
  epsilons: 
    type: choice
    options:
      - [0, 0.05, 0.1, 0.25]


GPRGNN:
  fixed:
    model_label: GPRGNN

  grid:
    model_params_add:
      robust_epsilon:
          type: choice
          options:
            - 0
            - 0.05
            - 0.1
            - 0.2
    seed:
      type: choice
      options:
        - 0
        - 1
        - 5

GCN:
  fixed:
    model_label: GCN

  grid:
    model_params_add:
      robust_epsilon:
          type: choice
          options:
            - 0
    seed:
      type: choice
      options:
        - 0
        - 1
        - 5
